[package]
name = "near-jsonrpc-test-utils"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
publish = false
edition = "2018"

[dependencies]
actix = "=0.11.0-beta.2"
awc = "3.0.0-beta.5"
lazy_static = "1.4"
futures = "0.3"
serde = "1"
serde_json = "1"

near-chain-configs = { path = "../../../core/chain-configs" }
near-primitives = { path = "../../../core/primitives" }
near-client = { path = "../../client" }
near-network = { path = "../../network" }
near-jsonrpc = { path = "../" }
near-jsonrpc-primitives = { path = "../../jsonrpc-primitives" }

[features]
test_features = ["near-jsonrpc/test_features"]
